name: Dexcom Mon

on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * *'

concurrency:
  group: dexcom-monitor-2
  cancel-in-progress: true

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Run Monitor
      env:
        TZ: America/New_York
        DISPLAY_NAME: ${{ secrets.DISPLAY_NAME }}
        DEXCOM_USERNAME: ${{ secrets.DEXCOM_USERNAME }}
        DEXCOM_PASSWORD: ${{ secrets.DEXCOM_PASSWORD }}
        NOTIFICATION_URI: ${{ secrets.NOTIFICATION_URI }}
        HEALTHCHECK_URI: ${{ secrets.HEALTHCHECK_URI }}
      run: |
        python -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-sync requirements/prod-requirements.txt
        python alert.py
